version: '3.9'

services:
  dagster:
    build:
      context: ./dagster
      dockerfile: Dockerfile
    container_name: dagster
    ports:
      - "3000:3000"
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./dagster:/opt/dagster/app
      - ./dagster/dagster_home:/opt/dagster/dagster_home
    command: >
      bash -c "
        dagster-daemon run & 
        dagster-webserver -m pipelines -h 0.0.0.0 -p 3000
      "
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: datalake
    volumes:
      - ./postgres:/var/lib/postgresql/data
